# Ensuring correct work dirrectory

In [119]:
import os
print("Current working directory:", os.getcwd())
print("Contents:", os.listdir("."))

Current working directory: d:\GITHUB\PROJECT 2\Python (cleaning)
Contents: ['s01.ipynb']

# Importing libraries and Data Sets CSV

PLEASE NOTE - instead of "../CSV_raw/cens_21empo_r2_linear_2_0.csv" or "../CSV_raw/cens_21loc_r2_linear_2_0.csv" you SHOULD insert your path to file!!!

In [120]:
import numpy as np
import pandas as pd

df2 = pd.read_csv("../CSV_raw/cens_21empo_r2_linear_2_0.csv")
df3 = pd.read_csv("../CSV_raw/cens_21loc_r2_linear_2_0.csv")

C:\Users\jk21r\AppData\Local\Temp\ipykernel_17596\4194952580.py:4: DtypeWarning: Columns (0: OBS_FLAG, 1: Observation status (Flag) V2 structure, 2: CONF_STATUS, 3: Confidentiality status (flag)) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("../CSV_raw/cens_21empo_r2_linear_2_0.csv")
C:\Users\jk21r\AppData\Local\Temp\ipykernel_17596\4194952580.py:5: DtypeWarning: Columns (0: OBS_FLAG, 1: Observation status (Flag) V2 structure, 2: CONF_STATUS, 3: Confidentiality status (flag)) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv("../CSV_raw/cens_21loc_r2_linear_2_0.csv")

# DISPLAY OPTIONS (see all columns)

Too much columns in datasets, but I want to display and see all of them. I am moving this line here, at the beginning, because I want to see all columns of df1, and I will use this option for all dataframes.

In [ ]:
pd.set_option('display.max_columns', None)

# ANALYSING data sets - DF2 Population by status in employment, age groups, occupation and NUTS 2 region

In [122]:
df2.head(10)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,wstatus,Labour force and employment status,isco08,International Standard Classification of Occupations 2008 (ISCO-08),age,Age class,sex,Sex,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT,Austria,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT1,Ostösterreich,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT11,Burgenland,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT12,Niederösterreich,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT13,Wien,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
5,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT2,Südösterreich,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
6,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT21,Kärnten,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
7,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT22,Steiermark,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
8,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT3,Westösterreich,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN
9,dataflow,ESTAT:CENS_21EMPO_R2(1.0),"Population by status in employment, age groups...",A,Annual,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT31,Oberösterreich,2021,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [123]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3415886 entries, 0 to 3415885
Data columns (total 25 columns):
 #   Column                                                               Dtype
---  ------                                                               -----
 0   STRUCTURE                                                            str
 1   STRUCTURE_ID                                                         str
 2   STRUCTURE_NAME                                                       str
 3   freq                                                                 str
 4   Time frequency                                                       str
 5   wstatus                                                              str
 6   Labour force and employment status                                   str
 7   isco08                                                               str
 8   International Standard Classification of Occupations 2008 (ISCO-08)  str
 9   age                                                                  str
 10  Age class                                                            str
 11  sex                                                                  str
 12  Sex                                                                  str
 13  unit                                                                 str
 14  Unit of measure                                                      str
 15  geo                                                                  str
 16  Geopolitical entity (reporting)                                      str
 17  TIME_PERIOD                                                          int64
 18  Time                                                                 float64
 19  OBS_VALUE                                                            float64
 20  Observation value                                                    float64
 21  OBS_FLAG                                                             str
 22  Observation status (Flag) V2 structure                               str
 23  CONF_STATUS                                                          str
 24  Confidentiality status (flag)                                        str
dtypes: float64(3), int64(1), str(21)
memory usage: 651.5 MB

In [124]:
df2.nunique() # Unique values in each column. This can help us understand the diversity of data in each column and identify potential categorical variables.

STRUCTURE                                                                  1
STRUCTURE_ID                                                               1
STRUCTURE_NAME                                                             1
freq                                                                       1
Time frequency                                                             1
wstatus                                                                    7
Labour force and employment status                                         7
isco08                                                                    13
International Standard Classification of Occupations 2008 (ISCO-08)       13
age                                                                       28
Age class                                                                 28
sex                                                                        3
Sex                                                                        3
unit                                                                       1
Unit of measure                                                            1
geo                                                                      448
Geopolitical entity (reporting)                                          356
TIME_PERIOD                                                                1
Time                                                                       0
OBS_VALUE                                                              93707
Observation value                                                          0
OBS_FLAG                                                                   3
Observation status (Flag) V2 structure                                     3
CONF_STATUS                                                                1
Confidentiality status (flag)                                              1
dtype: int64

Here I will show how I explore the columns and decide which of them stay. Also I would like to do some modifications to the columns.

In [125]:
df2['age'].unique()

<StringArray>
[  'TOTAL',  'Y10-14',  'Y15-19',  'Y15-29',  'Y20-24',  'Y25-29',  'Y30-34',
  'Y30-49',  'Y35-39',  'Y40-44',  'Y45-49',    'Y5-9',  'Y50-54',  'Y50-64',
  'Y55-59',  'Y60-64',  'Y65-69',  'Y65-84',  'Y70-74',  'Y75-79',  'Y80-84',
  'Y85-89',  'Y90-94',  'Y95-99', 'Y_GE100',  'Y_GE85',  'Y_LT15',   'Y_LT5']
Length: 28, dtype: str

In [126]:
df2['Age class'].unique()

<StringArray>
[              'Total', 'From 10 to 14 years', 'From 15 to 19 years',
 'From 15 to 29 years', 'From 20 to 24 years', 'From 25 to 29 years',
 'From 30 to 34 years', 'From 30 to 49 years', 'From 35 to 39 years',
 'From 40 to 44 years', 'From 45 to 49 years',   'From 5 to 9 years',
 'From 50 to 54 years', 'From 50 to 64 years', 'From 55 to 59 years',
 'From 60 to 64 years', 'From 65 to 69 years', 'From 65 to 84 years',
 'From 70 to 74 years', 'From 75 to 79 years', 'From 80 to 84 years',
 'From 85 to 89 years', 'From 90 to 94 years', 'From 95 to 99 years',
   '100 years or over',    '85 years or over',  'Less than 15 years',
   'Less than 5 years']
Length: 28, dtype: str

So, many columns are duplicates or simply not encoded. I would like to remove Age Class as its codified column "age" is easy to understand already, and also I will do modification to age column (Y_GE - I just don`t like how it sounds, lets rename it to Y_O (years_over)).

VERY IMPORTANT AND EASILY MISSED THING - AGGREGATED CATEGORIES!!!! We don`t need all these Y30-49, Y50-64, Y65-84, Y_LT15,  we already have separate categories for all of this, so we completely remove these completely.

Y_GE100 and Y_LT5 are aggregated, but their numbers are both under "Not Applicable" categories, so we can leave these categories. (100+ old people and babies don`t work, so no work category)

In [127]:
aggregated_ages = ['Y15-29', 'Y30-49', 'Y50-64', 'Y65-84', 'Y_GE85', 'Y_LT15']
df2 = df2[~df2['age'].isin(aggregated_ages)]
print(df2['age'].unique())

<StringArray>
[  'TOTAL',  'Y10-14',  'Y15-19',  'Y20-24',  'Y25-29',  'Y30-34',  'Y35-39',
  'Y40-44',  'Y45-49',    'Y5-9',  'Y50-54',  'Y55-59',  'Y60-64',  'Y65-69',
  'Y70-74',  'Y75-79',  'Y80-84',  'Y85-89',  'Y90-94',  'Y95-99', 'Y_GE100',
   'Y_LT5']
Length: 22, dtype: str

As we can ses above - I renamed the age categories to make them more consistent and easier to understand. Now, 'Y_GE100' is renamed to 'Y_O100' (indicating age 100 or older) and 'Y_GE85' is renamed to 'Y_O85' (indicating age 85 or older). 
This makes the age categories more intuitive and easier to interpret and I can remove Age class completely

In [128]:
df2['sex'].unique()

<StringArray>
['F', 'M', 'T']
Length: 3, dtype: str

In [129]:
df2['Sex'].unique()

<StringArray>
['Females', 'Males', 'Total']
Length: 3, dtype: str

In [130]:
print(df2.columns.tolist())

['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency', 'wstatus', 'Labour force and employment status', 'isco08', 'International Standard Classification of Occupations 2008 (ISCO-08)', 'age', 'Age class', 'sex', 'Sex', 'unit', 'Unit of measure', 'geo', 'Geopolitical entity (reporting)', 'TIME_PERIOD', 'Time', 'OBS_VALUE', 'Observation value', 'OBS_FLAG', 'Observation status (Flag) V2 structure', 'CONF_STATUS', 'Confidentiality status (flag)']

In [131]:
df2['wstatus'].unique()

<StringArray>
['CFAM_COOP', 'NAP', 'SAL', 'SELF_NS', 'SELF_S', 'TOTAL', 'UNK']
Length: 7, dtype: str

In [132]:
df2['Labour force and employment status'].unique()

<StringArray>
['Contributing family workers and members of producers' cooperatives',
                                                     'Not applicable',
                                                          'Employees',
      'Self-employed persons without employees (own-account workers)',
                   'Self-employed persons with employees (employers)',
                                                              'Total',
                                                            'Unknown']
Length: 7, dtype: str

Lets create a dictionary of columns to drop

After the above analysis I decide that I do not need a whole lot of columns, and I create a list with columns to drop bellow

In [133]:
cols_to_drop1 = [
    'STRUCTURE',
    'STRUCTURE_ID',
    'STRUCTURE_NAME',
    'freq',
    'Time frequency',
    'Age class',        
    'Sex',   
    'unit',
    'Unit of measure',
    'Time',            
    'Observation value', 
    'OBS_FLAG',
    'Observation status (Flag) V2 structure',
    'CONF_STATUS',
    'Confidentiality status (flag)'
]

There are columns like 
wstatus : 'CFAM_COOP', 'NAP', 'SAL', 'SELF_NS', 'SELF_S', 'UNK'
AND
Labour force and employment status : 'Contributing family workers and members of producers' cooperatives', 'Not applicable', 'Employees',
'Self-employed persons without employees (own-account workers)', 'Self-employed persons with employees (employers)', 'Unknown'

They are basicaly the same, but one is codified and other is not. I am leaving both such columns to understand what these abreviations mean.

Same goes for geo AND geopolitical entity (reporting), they are the same but I will leave them. They all are easily removed in PowerBI or even SQL, but I am leaving them for my convenience (and future report viewers convinience too!)

In [134]:
df2.drop(columns=cols_to_drop1, inplace=True, errors='ignore')
print(df2.columns.tolist())

['wstatus', 'Labour force and employment status', 'isco08', 'International Standard Classification of Occupations 2008 (ISCO-08)', 'age', 'sex', 'geo', 'Geopolitical entity (reporting)', 'TIME_PERIOD', 'OBS_VALUE']

In [135]:
df2.head(10)

,wstatus,Labour force and employment status,isco08,International Standard Classification of Occupations 2008 (ISCO-08),age,sex,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
0,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT,Austria,2021,0.0
1,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT1,Ostösterreich,2021,0.0
2,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT11,Burgenland,2021,0.0
3,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT12,Niederösterreich,2021,0.0
4,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT13,Wien,2021,0.0
5,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT2,Südösterreich,2021,0.0
6,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT21,Kärnten,2021,0.0
7,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT22,Steiermark,2021,0.0
8,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT3,Westösterreich,2021,0.0
9,CFAM_COOP,Contributing family workers and members of pro...,NAP,Not applicable,TOTAL,F,AT31,Oberösterreich,2021,0.0

Now, final step - remove TOTALS as I calculate them myself in visuals of POWER BI.

using unique I will check possible values of columns that may contain "TOTAL" or its variants.

In [136]:
df2['wstatus'].unique()

<StringArray>
['CFAM_COOP', 'NAP', 'SAL', 'SELF_NS', 'SELF_S', 'TOTAL', 'UNK']
Length: 7, dtype: str

In [137]:
df2['Labour force and employment status'].unique()

<StringArray>
['Contributing family workers and members of producers' cooperatives',
                                                     'Not applicable',
                                                          'Employees',
      'Self-employed persons without employees (own-account workers)',
                   'Self-employed persons with employees (employers)',
                                                              'Total',
                                                            'Unknown']
Length: 7, dtype: str

In [138]:
df2['isco08'].unique()

<StringArray>
[  'NAP',   'OC0',   'OC1',   'OC2',   'OC3',   'OC4',   'OC5',   'OC6',
   'OC7',   'OC8',   'OC9', 'TOTAL',   'UNK']
Length: 13, dtype: str

In [139]:
df2['International Standard Classification of Occupations 2008 (ISCO-08)'].unique()

<StringArray>
[                                    'Not applicable',
                           'Armed forces occupations',
                                           'Managers',
                                      'Professionals',
            'Technicians and associate professionals',
                           'Clerical support workers',
                          'Service and sales workers',
 'Skilled agricultural, forestry and fishery workers',
                   'Craft and related trades workers',
         'Plant and machine operators and assemblers',
                             'Elementary occupations',
                                              'Total',
                                            'Unknown']
Length: 13, dtype: str

In [140]:
df2['age'].unique()

<StringArray>
[  'TOTAL',  'Y10-14',  'Y15-19',  'Y20-24',  'Y25-29',  'Y30-34',  'Y35-39',
  'Y40-44',  'Y45-49',    'Y5-9',  'Y50-54',  'Y55-59',  'Y60-64',  'Y65-69',
  'Y70-74',  'Y75-79',  'Y80-84',  'Y85-89',  'Y90-94',  'Y95-99', 'Y_GE100',
   'Y_LT5']
Length: 22, dtype: str

In [141]:
df2['TIME_PERIOD'].unique()

array([2021])

In [142]:
df2['OBS_VALUE'].unique()

array([0.00000e+00,         nan, 3.10000e+01, ..., 7.52490e+04,
       1.76909e+05, 2.14980e+04], shape=(73860,))

In [143]:
df2['sex'].unique()

<StringArray>
['F', 'M', 'T']
Length: 3, dtype: str

Lets write a quick cicle to remove TOTAL rows from our Data.

In [144]:
cols_to_clean = ['wstatus', 'Labour force and employment status', 'isco08', 
                 'International Standard Classification of Occupations 2008 (ISCO-08)',
                 'Labour force and employment status',
                 'age', 'sex', 'geo']

for col in cols_to_clean:
    df2 = df2[df2[col].str.lower() != 'total']

and a small line to remove rows with "T" (meaning Total)

In [145]:
df2 = df2[df2['sex'].str.strip().str.upper() != 'T']

In [146]:
df2['isco08'].unique()

<StringArray>
['NAP', 'OC0', 'OC1', 'OC2', 'OC3', 'OC4', 'OC5', 'OC6', 'OC7', 'OC8', 'OC9',
 'UNK']
Length: 12, dtype: str

In [147]:
df2['age'].unique()

<StringArray>
[ 'Y10-14',  'Y15-19',  'Y20-24',  'Y25-29',  'Y30-34',  'Y35-39',  'Y40-44',
  'Y45-49',    'Y5-9',  'Y50-54',  'Y55-59',  'Y60-64',  'Y65-69',  'Y70-74',
  'Y75-79',  'Y80-84',  'Y85-89',  'Y90-94',  'Y95-99', 'Y_GE100',   'Y_LT5']
Length: 21, dtype: str

In [148]:
df2['wstatus'].unique()

<StringArray>
['CFAM_COOP', 'NAP', 'SAL', 'SELF_NS', 'SELF_S', 'UNK']
Length: 6, dtype: str

In [149]:
df2['Labour force and employment status'].unique()

<StringArray>
['Contributing family workers and members of producers' cooperatives',
                                                     'Not applicable',
                                                          'Employees',
      'Self-employed persons without employees (own-account workers)',
                   'Self-employed persons with employees (employers)',
                                                            'Unknown']
Length: 6, dtype: str

and just to be sure, lets remove 0 and NAN from OBS_VALUE

In [150]:
df2 = df2[(df2['OBS_VALUE'].notna()) & (df2['OBS_VALUE'] != 0)]

In [151]:
print("NaN:", df2['OBS_VALUE'].isna().sum())
print("0:", (df2['OBS_VALUE'] == 0).sum())

NaN: 0
0: 0

# FINAL RESULTS DF2

In [152]:
df2.head(10)

,wstatus,Labour force and employment status,isco08,International Standard Classification of Occupations 2008 (ISCO-08),age,sex,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
40513,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,FR,France,2021,6.0
40533,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,FRH,Bretagne,2021,1.0
40534,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,FRH0,Bretagne,2021,1.0
40535,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,FRI,Nouvelle-Aquitaine,2021,5.0
40537,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,FRI2,Limousin,2021,5.0
40625,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,LT,Lithuania,2021,72.0
40626,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,LT0,Lietuva,2021,72.0
40627,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,LT01,Sostinės regionas,2021,12.0
40628,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,LT02,Vidurio ir vakarų Lietuvos regionas,2021,62.0
40703,CFAM_COOP,Contributing family workers and members of pro...,OC0,Armed forces occupations,Y15-19,F,PT,Portugal,2021,24.0

I want to change column places for future convenience

In [153]:
df2 = df2[['isco08', 
           'International Standard Classification of Occupations 2008 (ISCO-08)', 
           'wstatus', 
           'Labour force and employment status', 
           'age', 
           'sex', 
           'geo', 
           'Geopolitical entity (reporting)', 
           'TIME_PERIOD', 
           'OBS_VALUE']]

In [154]:
df2.head(10)

,isco08,International Standard Classification of Occupations 2008 (ISCO-08),wstatus,Labour force and employment status,age,sex,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
40513,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,FR,France,2021,6.0
40533,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,FRH,Bretagne,2021,1.0
40534,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,FRH0,Bretagne,2021,1.0
40535,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,FRI,Nouvelle-Aquitaine,2021,5.0
40537,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,FRI2,Limousin,2021,5.0
40625,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,LT,Lithuania,2021,72.0
40626,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,LT0,Lietuva,2021,72.0
40627,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,LT01,Sostinės regionas,2021,12.0
40628,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,LT02,Vidurio ir vakarų Lietuvos regionas,2021,62.0
40703,OC0,Armed forces occupations,CFAM_COOP,Contributing family workers and members of pro...,Y15-19,F,PT,Portugal,2021,24.0

# ANALYSING data sets - DF3 Population by location of place of work, age groups, occupation and NUTS 2 region

In [155]:
df3.head(10)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,isco08,International Standard Classification of Occupations 2008 (ISCO-08),workplace,Place of work,age,Age class,sex,Sex,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT,Austria,2021,NaN,2473557.0,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT1,Ostösterreich,2021,NaN,1106103.0,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT11,Burgenland,2021,NaN,84988.0,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT12,Niederösterreich,2021,NaN,465003.0,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT13,Wien,2021,NaN,556112.0,NaN,NaN,NaN,NaN,NaN
5,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT2,Südösterreich,2021,NaN,506846.0,NaN,NaN,NaN,NaN,NaN
6,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT21,Kärnten,2021,NaN,163052.0,NaN,NaN,NaN,NaN,NaN
7,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT22,Steiermark,2021,NaN,343794.0,NaN,NaN,NaN,NaN,NaN
8,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT3,Westösterreich,2021,NaN,860608.0,NaN,NaN,NaN,NaN,NaN
9,dataflow,ESTAT:CENS_21LOC_R2(1.0),"Population by location of place of work, age g...",A,Annual,NAP,Not applicable,NAP,Not applicable,TOTAL,Total,F,Females,NR,Number,AT31,Oberösterreich,2021,NaN,400138.0,NaN,NaN,NaN,NaN,NaN

In [156]:
df3['workplace'].unique()

<StringArray>
['NAP', 'NAT_IN', 'NAT_OUT', 'NFIX', 'TOTAL', 'UNK']
Length: 6, dtype: str

In [157]:
df3['Place of work'].unique()

<StringArray>
[                               'Not applicable',
     'In the territory of the reporting country',
 'Not in the territory of the reporting country',
                                     'Not fixed',
                                         'Total',
                                       'Unknown']
Length: 6, dtype: str

In [158]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930757 entries, 0 to 2930756
Data columns (total 25 columns):
 #   Column                                                               Dtype
---  ------                                                               -----
 0   STRUCTURE                                                            str
 1   STRUCTURE_ID                                                         str
 2   STRUCTURE_NAME                                                       str
 3   freq                                                                 str
 4   Time frequency                                                       str
 5   isco08                                                               str
 6   International Standard Classification of Occupations 2008 (ISCO-08)  str
 7   workplace                                                            str
 8   Place of work                                                        str
 9   age                                                                  str
 10  Age class                                                            str
 11  sex                                                                  str
 12  Sex                                                                  str
 13  unit                                                                 str
 14  Unit of measure                                                      str
 15  geo                                                                  str
 16  Geopolitical entity (reporting)                                      str
 17  TIME_PERIOD                                                          int64
 18  Time                                                                 float64
 19  OBS_VALUE                                                            float64
 20  Observation value                                                    float64
 21  OBS_FLAG                                                             str
 22  Observation status (Flag) V2 structure                               str
 23  CONF_STATUS                                                          str
 24  Confidentiality status (flag)                                        str
dtypes: float64(3), int64(1), str(21)
memory usage: 559.0 MB

In [159]:
df3.nunique()

STRUCTURE                                                                  1
STRUCTURE_ID                                                               1
STRUCTURE_NAME                                                             1
freq                                                                       1
Time frequency                                                             1
isco08                                                                    13
International Standard Classification of Occupations 2008 (ISCO-08)       13
workplace                                                                  6
Place of work                                                              6
age                                                                       28
Age class                                                                 28
sex                                                                        3
Sex                                                                        3
unit                                                                       1
Unit of measure                                                            1
geo                                                                      448
Geopolitical entity (reporting)                                          356
TIME_PERIOD                                                                1
Time                                                                       0
OBS_VALUE                                                              93378
Observation value                                                          0
OBS_FLAG                                                                   3
Observation status (Flag) V2 structure                                     3
CONF_STATUS                                                                1
Confidentiality status (flag)                                              1
dtype: int64

In [160]:
df3['age'].unique()

<StringArray>
[  'TOTAL',  'Y10-14',  'Y15-19',  'Y15-29',  'Y20-24',  'Y25-29',  'Y30-34',
  'Y30-49',  'Y35-39',  'Y40-44',  'Y45-49',    'Y5-9',  'Y50-54',  'Y50-64',
  'Y55-59',  'Y60-64',  'Y65-69',  'Y65-84',  'Y70-74',  'Y75-79',  'Y80-84',
  'Y85-89',  'Y90-94',  'Y95-99', 'Y_GE100',  'Y_GE85',  'Y_LT15',   'Y_LT5']
Length: 28, dtype: str

In [161]:
aggregated_ages2 = ['Y15-29', 'Y30-49', 'Y50-64', 'Y65-84', 'Y_GE85', 'Y_LT15']
df3 = df3[~df3['age'].isin(aggregated_ages2)]
print(df3['age'].unique())

<StringArray>
[  'TOTAL',  'Y10-14',  'Y15-19',  'Y20-24',  'Y25-29',  'Y30-34',  'Y35-39',
  'Y40-44',  'Y45-49',    'Y5-9',  'Y50-54',  'Y55-59',  'Y60-64',  'Y65-69',
  'Y70-74',  'Y75-79',  'Y80-84',  'Y85-89',  'Y90-94',  'Y95-99', 'Y_GE100',
   'Y_LT5']
Length: 22, dtype: str

In [162]:
print(df3.columns.tolist())

['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'freq', 'Time frequency', 'isco08', 'International Standard Classification of Occupations 2008 (ISCO-08)', 'workplace', 'Place of work', 'age', 'Age class', 'sex', 'Sex', 'unit', 'Unit of measure', 'geo', 'Geopolitical entity (reporting)', 'TIME_PERIOD', 'Time', 'OBS_VALUE', 'Observation value', 'OBS_FLAG', 'Observation status (Flag) V2 structure', 'CONF_STATUS', 'Confidentiality status (flag)']

In [163]:
cols_to_drop2 = [
    'STRUCTURE',
    'STRUCTURE_ID',
    'STRUCTURE_NAME',
    'freq',
    'Time frequency',
    'Age class',
    'Sex',   
    'unit',
    'Unit of measure',
    'Time',
    'Observation value', 
    'OBS_FLAG',
    'Observation status (Flag) V2 structure',
    'CONF_STATUS',
    'Confidentiality status (flag)'
]

In [164]:
df3.drop(columns=cols_to_drop2, inplace=True, errors='ignore')

In [165]:
df3.head(10)

,isco08,International Standard Classification of Occupations 2008 (ISCO-08),workplace,Place of work,age,sex,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
0,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT,Austria,2021,2473557.0
1,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT1,Ostösterreich,2021,1106103.0
2,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT11,Burgenland,2021,84988.0
3,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT12,Niederösterreich,2021,465003.0
4,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT13,Wien,2021,556112.0
5,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT2,Südösterreich,2021,506846.0
6,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT21,Kärnten,2021,163052.0
7,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT22,Steiermark,2021,343794.0
8,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT3,Westösterreich,2021,860608.0
9,NAP,Not applicable,NAP,Not applicable,TOTAL,F,AT31,Oberösterreich,2021,400138.0

In [166]:
df3['workplace'].unique()

<StringArray>
['NAP', 'NAT_IN', 'NAT_OUT', 'NFIX', 'TOTAL', 'UNK']
Length: 6, dtype: str

In [167]:
df3['isco08'].unique()

<StringArray>
[  'NAP',   'OC0',   'OC1',   'OC2',   'OC3',   'OC4',   'OC5',   'OC6',
   'OC7',   'OC8',   'OC9', 'TOTAL',   'UNK']
Length: 13, dtype: str

In [168]:
df3['International Standard Classification of Occupations 2008 (ISCO-08)'].unique()

<StringArray>
[                                    'Not applicable',
                           'Armed forces occupations',
                                           'Managers',
                                      'Professionals',
            'Technicians and associate professionals',
                           'Clerical support workers',
                          'Service and sales workers',
 'Skilled agricultural, forestry and fishery workers',
                   'Craft and related trades workers',
         'Plant and machine operators and assemblers',
                             'Elementary occupations',
                                              'Total',
                                            'Unknown']
Length: 13, dtype: str

In [169]:
cols_to_clean2 = ['isco08', 'International Standard Classification of Occupations 2008 (ISCO-08)',
                  'Geopolitical entity (reporting)',  
                 'workplace','age', 'sex', 'geo']

for col in cols_to_clean2:
    df3 = df3[df3[col].str.lower() != 'total']

In [170]:
df3 = df3[df3['sex'].str.strip().str.upper() != 'T']

In [171]:
df3['workplace'].unique()

<StringArray>
['NAP', 'NAT_IN', 'NAT_OUT', 'NFIX', 'UNK']
Length: 5, dtype: str

In [172]:
df3 = df3[(df3['OBS_VALUE'].notna()) & (df3['OBS_VALUE'] != 0)]

In [173]:
print("NaN:", df3['OBS_VALUE'].isna().sum())
print("0:", (df3['OBS_VALUE'] == 0).sum())

NaN: 0
0: 0

FINAL RESULT

In [174]:
df3.head(10)

,isco08,International Standard Classification of Occupations 2008 (ISCO-08),workplace,Place of work,age,sex,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
1341,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT,Austria,2021,206202.0
1342,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT1,Ostösterreich,2021,90096.0
1343,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT11,Burgenland,2021,6662.0
1344,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT12,Niederösterreich,2021,40397.0
1345,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT13,Wien,2021,43037.0
1346,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT2,Südösterreich,2021,39469.0
1347,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT21,Kärnten,2021,12403.0
1348,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT22,Steiermark,2021,27066.0
1349,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT3,Westösterreich,2021,76637.0
1350,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT31,Oberösterreich,2021,35987.0

I would like to change column placement in table

In [175]:
df3 = df3[['isco08', 
           'International Standard Classification of Occupations 2008 (ISCO-08)', 
           'workplace', 
           'Place of work', 
           'age', 
           'sex', 
           'geo', 
           'Geopolitical entity (reporting)', 
           'TIME_PERIOD', 
           'OBS_VALUE']]

In [176]:
df3.head(10)

,isco08,International Standard Classification of Occupations 2008 (ISCO-08),workplace,Place of work,age,sex,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
1341,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT,Austria,2021,206202.0
1342,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT1,Ostösterreich,2021,90096.0
1343,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT11,Burgenland,2021,6662.0
1344,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT12,Niederösterreich,2021,40397.0
1345,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT13,Wien,2021,43037.0
1346,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT2,Südösterreich,2021,39469.0
1347,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT21,Kärnten,2021,12403.0
1348,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT22,Steiermark,2021,27066.0
1349,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT3,Westösterreich,2021,76637.0
1350,NAP,Not applicable,NAP,Not applicable,Y10-14,F,AT31,Oberösterreich,2021,35987.0

# Exporting to CSV

In [177]:
df2.to_csv("../CSV_clean/df2_clean.csv", index=False, encoding='utf-8-sig')
df3.to_csv("../CSV_clean/df3_clean.csv", index=False, encoding='utf-8-sig')